name: Trigger Site Rebuild 

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main 

jobs:
  trigger-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CHARMOS_SITE_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/bluegummi/charmos-site/dispatches \
            -d '{"event_type": "remote-trigger"}'
